// Generated by Wrangler on Tue Aug 27 2024 00:04:26 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  BUN_VERSION: '1.1.23'
  MICROCMS_SERVICE_DOMAIN: string
  MICROCMS_API_KEY: string
}
