// Generated by Wrangler on Mon Sep 02 2024 14:58:54 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  ENV: string
  BASE_URL: string
  GA_TRACKING_ID: string
  MICROCMS_SERVICE_DOMAIN: string
  MICROCMS_API_KEY: string
  SUPABASE_URL: string
  SUPABASE_ANON_KEY: string
  SUPABASE_DB_PASSWORD: string
}
