// Generated by Wrangler on Thu Sep 05 2024 23:32:54 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  ENV: string
  BASE_URL: string
  GA_TRACKING_ID: string
  MICROCMS_SERVICE_DOMAIN: string
  MICROCMS_API_KEY: string
  SUPABASE_URL: string
  SUPABASE_ANON_KEY: string
  DATABASE_PASSWORD: string
  DISCORD_CONTACT_WEBHOOK_URL: string
}
